name: Build and test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.16

      - name: Build
        run: go build -v -o publish/coronacheck-idemix ./

      - name: Publish archive with artifacts
        uses: actions/upload-artifact@v2
        with:
          name: publish-folder
          path: |
            publish

      - name: Test
        run: go test -v ./...